version: '3'

services:
  myredis:
    image: 'redis:alpine'
  mypostgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /home/varist/school/databasedata:/var/lib/postgresql/data
  mybackend:
    build:
      dockerfile: Dockerfile.dev
      context: mybackend/
    volumes:
      - /opt/app/node_modules
      - ./mybackend:/opt/app
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "9090:9000"
  mynginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: mynginx/
    ports:
      - "9000:80"
  myfrontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./myfrontend
    volumes:
      - /opt/app/node_modules
      - ./myfrontend:/opt/app
    ports:
      - "8080:8080"
