version: '3'

services:
  myredis:
    image: 'redis:alpine'

  mypostgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /home/varist/school/databasedata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U 1234user -d mydb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mybackend:
    build:
      dockerfile: Dockerfile.dev
      context: mybackend/
    volumes:
      - /opt/app/node_modules
      - ./mybackend:/opt/app
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      mypostgres:
        condition: service_healthy
    ports:
      - "9090:9000"

  mynginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./mynginx
    ports:
      - 80:80
    depends_on:
      - mybackend
      - myfrontend

  myfrontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./myfrontend
    volumes:
      - /opt/app/node_modules
      - ./myfrontend:/opt/app
    ports:
      - "8080:8080"
